// <auto-generated />
using LittleLibraryAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LittleLibraryAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260217115306_QuotesAdded")]
    partial class QuotesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LittleLibraryAPI.Models.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "F. Scott Fitzgerald",
                            genre = "Fiction",
                            title = "The Great Gatsby"
                        },
                        new
                        {
                            id = 2,
                            author = "Harper Lee",
                            genre = "Fiction",
                            title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            id = 3,
                            author = "George Orwell",
                            genre = "Dystopian",
                            title = "1984"
                        },
                        new
                        {
                            id = 4,
                            author = "Jane Austen",
                            genre = "Romance",
                            title = "Pride and Prejudice"
                        },
                        new
                        {
                            id = 5,
                            author = "J.R.R. Tolkien",
                            genre = "Fantasy",
                            title = "The Hobbit"
                        });
                });

            modelBuilder.Entity("LittleLibraryAPI.Models.Quote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "Oscar Wilde",
                            text = "Be yourself; everyone else is already taken."
                        },
                        new
                        {
                            id = 2,
                            author = "Marilyn Monroe",
                            text = "I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best."
                        },
                        new
                        {
                            id = 3,
                            author = "Frank Zappa",
                            text = "So many books, so little time."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
